---

extra_capabilities: [ "OpenSSH.Server~~~~0.0.1.0" ]
specialize_scripts: [ "/Users/spacecadet/Workspace/etc/deploy_scripts" ]

image_boot_partition_size: "16GB"

cloudbase_config_options:
  - section: DEFAULT
    option: username
    value: Cloudbase-Init

  - section: DEFAULT
    option: winrm_enable_basic_auth
    value: "false"