---

# Installation

- name: Install Curtin Hooks
  import_tasks: curtin_hooks.yml
  when: install_maas_hooks is defined and install_maas_hooks

- name: Install Windows Updates
  import_tasks: windows_update.yml
  when: install_windows_updates is defined and install_windows_updates

<<<<<<< Updated upstream
# Configuration
=======
- name: Install Extra Capabilities
  import_tasks: extra_capabilities.yml
  when: extra_capabilities is defined and (extra_capabilities|length>0)

- name: Install Extra MSI Packages
  import_tasks: extra_msi_packages.yml
  when: extra_msi_package_dirs is defined and (extra_msi_package_dirs|length>0)

- name: Install Windows Admin Center
  import_tasks: windows_admin_center.yml
  when: install_windows_admin_center is defined and install_windows_admin_center
>>>>>>> Stashed changes

- name: Disable hybrid boot
  import_tasks: disable_fast_startup.yml

<<<<<<< Updated upstream
=======
- name: Copy Deployment Scripts
  import_tasks: specialize_scripts.yml
  when: specialize_scripts is defined and (specialize_scripts|length>0)
  
>>>>>>> Stashed changes
# Clean up

- name: Disk Cleanup
  import_tasks: disk_cleanup.yml

- name: Compact Disk
  import_tasks: compact.yml

- name: Shrink Partition
  import_tasks: partition.yml

- name: Sysprep Generalize
  import_tasks: sysprep.yml