---
- name: Partitioning | Get minimum supported disk size
  win_shell: (Get-PartitionSupportedSize -DriveLetter C).SizeMin
  register: partition_size_result

- name: Partitioning | Shrink partition logical size
  block:
    - name: Partitioning | Update facts 
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"
    - name: Partitioning | Set partition size
      win_partition:
        partition_size: "{{ partition_size }}B"
        drive_letter: C
  rescue:
    - name: Partitioning | Failed to partition boot drive
      fail:
        msg: Failed to partition boot drive.
      when: retry_count | int == retries
    - name: Partitioning | Re-attempt partitioning
      include_tasks: partition.yml
  vars:
<<<<<<< Updated upstream
    step_size: "{{ '100MB' | human_to_bytes | int }}"
    raw_partition_size: "{{ partition_size_result.stdout | int | human_readable(unit='M') | human_to_bytes }}"
    partition_size: "{{ (raw_partition_size | int) // (step_size | int) * (step_size | int) + (step_size | int) }}"


=======
    retries: 20
    step_size: "{{ ('100MB'|human_to_bytes|int) }}"
    actual_size: "{{partition_size_result.stdout|int|human_readable(unit='M')|human_to_bytes|int}}"
    used_partition_size: "{{ actual_size if image_boot_partition_size is not defined else (image_boot_partition_size|human_to_bytes|int) }}"
    partition_size: "{{ (used_partition_size|int) // (step_size|int) * (step_size|int) + (step_size|int * retry_count|default(0)|int) }}"
>>>>>>> Stashed changes
  