---
- name: Sysprep | Register scheduled task to Sysprep /generalize
  win_scheduled_task:
    name: sysprep-generalize
    username: SYSTEM
    disallow_start_if_on_batteries: no
    stop_if_going_on_batteries: no
    actions:
    - path: powershell.exe
      arguments: "/c \"Set-Item WSMan:\\localhost\\Service\\AllowUnencrypted $false\""
    - path: C:\\windows\\system32\\sysprep\\sysprep.exe
      arguments: "/generalize /oobe /shutdown /quiet /unattend:\"{{ sysprep_deploy_unattend }}\""
    triggers:
    - type: registration

